### ISSUE TITLE
Previous Year Power Budget

### ISSUE THREAD

**Issue by anthonysteel** [queens-satellite-team/moc_sat#29]
Do we have a document that someone worked up for the power budget on the actual sat? @JoshW7 @emmapaczkowski

**Comment by JoshW7** [comment]
Yeah, [this ](https://queensuca-my.sharepoint.com/:x:/g/personal/16mrb3_queensu_ca/EUNPwYA5jlxKlGRnGlVacuYBbmIUH0zipZiT5EtnqX6hTg?e=1aSgPf)is what we made last year. You may need to be signed in to your queens account to view it.

**Comment by anthonysteel** [comment]
Excellent, exactly what I was looking for.
